part of '../fx_icon_categories.dart';

final class FxSolarIconsBiology {
  const FxSolarIconsBiology();

  final String _path = 'biology';

  FxAssetIcon get atomBoldDuotone => FxAssetIcon(name: '$_path/atom-bold-duotone');
  FxAssetIcon get atomBold => FxAssetIcon(name: '$_path/atom-bold');
  FxAssetIcon get atomBroken => FxAssetIcon(name: '$_path/atom-broken');
  FxAssetIcon get atomLineDuotone => FxAssetIcon(name: '$_path/atom-line-duotone');
  FxAssetIcon get atomLinear => FxAssetIcon(name: '$_path/atom-linear');
  FxAssetIcon get atomOutline => FxAssetIcon(name: '$_path/atom-outline');
  FxAssetIcon get bacteriaBoldDuotone => FxAssetIcon(name: '$_path/bacteria-bold-duotone');
  FxAssetIcon get bacteriaBold => FxAssetIcon(name: '$_path/bacteria-bold');
  FxAssetIcon get bacteriaBroken => FxAssetIcon(name: '$_path/bacteria-broken');
  FxAssetIcon get bacteriaLineDuotone => FxAssetIcon(name: '$_path/bacteria-line-duotone');
  FxAssetIcon get bacteriaLinear => FxAssetIcon(name: '$_path/bacteria-linear');
  FxAssetIcon get bacteriaOutline => FxAssetIcon(name: '$_path/bacteria-outline');
  FxAssetIcon get benzeneRingBoldDuotone => FxAssetIcon(name: '$_path/benzene-ring-bold-duotone');
  FxAssetIcon get benzeneRingBold => FxAssetIcon(name: '$_path/benzene-ring-bold');
  FxAssetIcon get benzeneRingBroken => FxAssetIcon(name: '$_path/benzene-ring-broken');
  FxAssetIcon get benzeneRingLineDuotone => FxAssetIcon(name: '$_path/benzene-ring-line-duotone');
  FxAssetIcon get benzeneRingLinear => FxAssetIcon(name: '$_path/benzene-ring-linear');
  FxAssetIcon get benzeneRingOutline => FxAssetIcon(name: '$_path/benzene-ring-outline');
  FxAssetIcon get boneBoldDuotone => FxAssetIcon(name: '$_path/bone-bold-duotone');
  FxAssetIcon get boneBold => FxAssetIcon(name: '$_path/bone-bold');
  FxAssetIcon get boneBrokenBoldDuotone => FxAssetIcon(name: '$_path/bone-broken-bold-duotone');
  FxAssetIcon get boneBrokenBold => FxAssetIcon(name: '$_path/bone-broken-bold');
  FxAssetIcon get boneBrokenBroken => FxAssetIcon(name: '$_path/bone-broken-broken');
  FxAssetIcon get boneBrokenLineDuotone => FxAssetIcon(name: '$_path/bone-broken-line-duotone');
  FxAssetIcon get boneBrokenLinear => FxAssetIcon(name: '$_path/bone-broken-linear');
  FxAssetIcon get boneBrokenOutline => FxAssetIcon(name: '$_path/bone-broken-outline');
  FxAssetIcon get boneBroken => FxAssetIcon(name: '$_path/bone-broken');
  FxAssetIcon get boneCrackBoldDuotone => FxAssetIcon(name: '$_path/bone-crack-bold-duotone');
  FxAssetIcon get boneCrackBold => FxAssetIcon(name: '$_path/bone-crack-bold');
  FxAssetIcon get boneCrackBroken => FxAssetIcon(name: '$_path/bone-crack-broken');
  FxAssetIcon get boneCrackLineDuotone => FxAssetIcon(name: '$_path/bone-crack-line-duotone');
  FxAssetIcon get boneCrackLinear => FxAssetIcon(name: '$_path/bone-crack-linear');
  FxAssetIcon get boneCrackOutline => FxAssetIcon(name: '$_path/bone-crack-outline');
  FxAssetIcon get boneLineDuotone => FxAssetIcon(name: '$_path/bone-line-duotone');
  FxAssetIcon get boneLinear => FxAssetIcon(name: '$_path/bone-linear');
  FxAssetIcon get boneOutline => FxAssetIcon(name: '$_path/bone-outline');
  FxAssetIcon get bonesBoldDuotone => FxAssetIcon(name: '$_path/bones-bold-duotone');
  FxAssetIcon get bonesBold => FxAssetIcon(name: '$_path/bones-bold');
  FxAssetIcon get bonesBroken => FxAssetIcon(name: '$_path/bones-broken');
  FxAssetIcon get bonesLineDuotone => FxAssetIcon(name: '$_path/bones-line-duotone');
  FxAssetIcon get bonesLinear => FxAssetIcon(name: '$_path/bones-linear');
  FxAssetIcon get bonesOutline => FxAssetIcon(name: '$_path/bones-outline');
  FxAssetIcon get dnaBoldDuotone => FxAssetIcon(name: '$_path/dna-bold-duotone');
  FxAssetIcon get dnaBold => FxAssetIcon(name: '$_path/dna-bold');
  FxAssetIcon get dnaBroken => FxAssetIcon(name: '$_path/dna-broken');
  FxAssetIcon get dnaLineDuotone => FxAssetIcon(name: '$_path/dna-line-duotone');
  FxAssetIcon get dnaLinear => FxAssetIcon(name: '$_path/dna-linear');
  FxAssetIcon get dnaOutline => FxAssetIcon(name: '$_path/dna-outline');
  FxAssetIcon get virusBoldDuotone => FxAssetIcon(name: '$_path/virus-bold-duotone');
  FxAssetIcon get virusBold => FxAssetIcon(name: '$_path/virus-bold');
  FxAssetIcon get virusBroken => FxAssetIcon(name: '$_path/virus-broken');
  FxAssetIcon get virusLineDuotone => FxAssetIcon(name: '$_path/virus-line-duotone');
  FxAssetIcon get virusLinear => FxAssetIcon(name: '$_path/virus-linear');
  FxAssetIcon get virusOutline => FxAssetIcon(name: '$_path/virus-outline');
}
