part of '../fx_icon_categories.dart';

final class FxSolarIconsCreative {
  const FxSolarIconsCreative();

  final String _path = ''; // 'creative';

  FxAssetIcon get colourTuneingBoldDuotone => FxAssetIcon(name: '${_path}colour-tuneing-bold-duotone');
  FxAssetIcon get colourTuneingBold => FxAssetIcon(name: '${_path}colour-tuneing-bold');
  FxAssetIcon get colourTuneingBroken => FxAssetIcon(name: '${_path}colour-tuneing-broken');
  FxAssetIcon get colourTuneingLineDuotone => FxAssetIcon(name: '${_path}colour-tuneing-line-duotone');
  FxAssetIcon get colourTuneingLinear => FxAssetIcon(name: '${_path}colour-tuneing-linear');
  FxAssetIcon get colourTuneingOutline => FxAssetIcon(name: '${_path}colour-tuneing-outline');
  FxAssetIcon get cosmeticBoldDuotone => FxAssetIcon(name: '${_path}cosmetic-bold-duotone');
  FxAssetIcon get cosmeticBold => FxAssetIcon(name: '${_path}cosmetic-bold');
  FxAssetIcon get cosmeticBroken => FxAssetIcon(name: '${_path}cosmetic-broken');
  FxAssetIcon get cosmeticLineDuotone => FxAssetIcon(name: '${_path}cosmetic-line-duotone');
  FxAssetIcon get cosmeticLinear => FxAssetIcon(name: '${_path}cosmetic-linear');
  FxAssetIcon get cosmeticOutline => FxAssetIcon(name: '${_path}cosmetic-outline');
  FxAssetIcon get magicStick2BoldDuotone => FxAssetIcon(name: '${_path}magic-stick-2-bold-duotone');
  FxAssetIcon get magicStick2Bold => FxAssetIcon(name: '${_path}magic-stick-2-bold');
  FxAssetIcon get magicStick2Broken => FxAssetIcon(name: '${_path}magic-stick-2-broken');
  FxAssetIcon get magicStick2LineDuotone => FxAssetIcon(name: '${_path}magic-stick-2-line-duotone');
  FxAssetIcon get magicStick2Linear => FxAssetIcon(name: '${_path}magic-stick-2-linear');
  FxAssetIcon get magicStick2Outline => FxAssetIcon(name: '${_path}magic-stick-2-outline');
  FxAssetIcon get magicStick3BoldDuotone => FxAssetIcon(name: '${_path}magic-stick-3-bold-duotone');
  FxAssetIcon get magicStick3Bold => FxAssetIcon(name: '${_path}magic-stick-3-bold');
  FxAssetIcon get magicStick3Broken => FxAssetIcon(name: '${_path}magic-stick-3-broken');
  FxAssetIcon get magicStick3LineDuotone => FxAssetIcon(name: '${_path}magic-stick-3-line-duotone');
  FxAssetIcon get magicStick3Linear => FxAssetIcon(name: '${_path}magic-stick-3-linear');
  FxAssetIcon get magicStick3Outline => FxAssetIcon(name: '${_path}magic-stick-3-outline');
  FxAssetIcon get magicStickBoldDuotone => FxAssetIcon(name: '${_path}magic-stick-bold-duotone');
  FxAssetIcon get magicStickBold => FxAssetIcon(name: '${_path}magic-stick-bold');
  FxAssetIcon get magicStickBroken => FxAssetIcon(name: '${_path}magic-stick-broken');
  FxAssetIcon get magicStickLineDuotone => FxAssetIcon(name: '${_path}magic-stick-line-duotone');
  FxAssetIcon get magicStickLinear => FxAssetIcon(name: '${_path}magic-stick-linear');
  FxAssetIcon get magicStickOutline => FxAssetIcon(name: '${_path}magic-stick-outline');
  FxAssetIcon get paintRollerBoldDuotone => FxAssetIcon(name: '${_path}paint-roller-bold-duotone');
  FxAssetIcon get paintRollerBold => FxAssetIcon(name: '${_path}paint-roller-bold');
  FxAssetIcon get paintRollerBroken => FxAssetIcon(name: '${_path}paint-roller-broken');
  FxAssetIcon get paintRollerLineDuotone => FxAssetIcon(name: '${_path}paint-roller-line-duotone');
  FxAssetIcon get paintRollerLinear => FxAssetIcon(name: '${_path}paint-roller-linear');
  FxAssetIcon get paintRollerOutline => FxAssetIcon(name: '${_path}paint-roller-outline');
  FxAssetIcon get paletteBoldDuotone => FxAssetIcon(name: '${_path}palette-bold-duotone');
  FxAssetIcon get paletteBold => FxAssetIcon(name: '${_path}palette-bold');
  FxAssetIcon get paletteBroken => FxAssetIcon(name: '${_path}palette-broken');
  FxAssetIcon get paletteLineDuotone => FxAssetIcon(name: '${_path}palette-line-duotone');
  FxAssetIcon get paletteLinear => FxAssetIcon(name: '${_path}palette-linear');
  FxAssetIcon get paletteOutline => FxAssetIcon(name: '${_path}palette-outline');
  FxAssetIcon get paletteRoundBoldDuotone => FxAssetIcon(name: '${_path}palette-round-bold-duotone');
  FxAssetIcon get paletteRoundBold => FxAssetIcon(name: '${_path}palette-round-bold');
  FxAssetIcon get paletteRoundBroken => FxAssetIcon(name: '${_path}palette-round-broken');
  FxAssetIcon get paletteRoundLineDuotone => FxAssetIcon(name: '${_path}palette-round-line-duotone');
  FxAssetIcon get paletteRoundLinear => FxAssetIcon(name: '${_path}palette-round-linear');
  FxAssetIcon get paletteRoundOutline => FxAssetIcon(name: '${_path}palette-round-outline');
  FxAssetIcon get pallete2BoldDuotone => FxAssetIcon(name: '${_path}pallete-2-bold-duotone');
  FxAssetIcon get pallete2Bold => FxAssetIcon(name: '${_path}pallete-2-bold');
  FxAssetIcon get pallete2Broken => FxAssetIcon(name: '${_path}pallete-2-broken');
  FxAssetIcon get pallete2LineDuotone => FxAssetIcon(name: '${_path}pallete-2-line-duotone');
  FxAssetIcon get pallete2Linear => FxAssetIcon(name: '${_path}pallete-2-linear');
  FxAssetIcon get pallete2Outline => FxAssetIcon(name: '${_path}pallete-2-outline');
  FxAssetIcon get pipetteBoldDuotone => FxAssetIcon(name: '${_path}pipette-bold-duotone');
  FxAssetIcon get pipetteBold => FxAssetIcon(name: '${_path}pipette-bold');
  FxAssetIcon get pipetteBroken => FxAssetIcon(name: '${_path}pipette-broken');
  FxAssetIcon get pipetteLineDuotone => FxAssetIcon(name: '${_path}pipette-line-duotone');
  FxAssetIcon get pipetteLinear => FxAssetIcon(name: '${_path}pipette-linear');
  FxAssetIcon get pipetteOutline => FxAssetIcon(name: '${_path}pipette-outline');
}
