part of '../fx_icon_categories.dart';

final class FxSolarIconsDesign {
  const FxSolarIconsDesign();

  final String _path = 'design';

  FxAssetIcon get cropBoldDuotone => FxAssetIcon(name: '$_path/crop-bold-duotone');
  FxAssetIcon get cropBold => FxAssetIcon(name: '$_path/crop-bold');
  FxAssetIcon get cropBroken => FxAssetIcon(name: '$_path/crop-broken');
  FxAssetIcon get cropLineDuotone => FxAssetIcon(name: '$_path/crop-line-duotone');
  FxAssetIcon get cropLinear => FxAssetIcon(name: '$_path/crop-linear');
  FxAssetIcon get cropMinimalisticBoldDuotone => FxAssetIcon(name: '$_path/crop-minimalistic-bold-duotone');
  FxAssetIcon get cropMinimalisticBold => FxAssetIcon(name: '$_path/crop-minimalistic-bold');
  FxAssetIcon get cropMinimalisticBroken => FxAssetIcon(name: '$_path/crop-minimalistic-broken');
  FxAssetIcon get cropMinimalisticLineDuotone => FxAssetIcon(name: '$_path/crop-minimalistic-line-duotone');
  FxAssetIcon get cropMinimalisticLinear => FxAssetIcon(name: '$_path/crop-minimalistic-linear');
  FxAssetIcon get cropMinimalisticOutline => FxAssetIcon(name: '$_path/crop-minimalistic-outline');
  FxAssetIcon get cropOutline => FxAssetIcon(name: '$_path/crop-outline');
  FxAssetIcon get filtersBoldDuotone => FxAssetIcon(name: '$_path/filters-bold-duotone');
  FxAssetIcon get filtersBold => FxAssetIcon(name: '$_path/filters-bold');
  FxAssetIcon get filtersBroken => FxAssetIcon(name: '$_path/filters-broken');
  FxAssetIcon get filtersLineDuotone => FxAssetIcon(name: '$_path/filters-line-duotone');
  FxAssetIcon get filtersLinear => FxAssetIcon(name: '$_path/filters-linear');
  FxAssetIcon get filtersOutline => FxAssetIcon(name: '$_path/filters-outline');
  FxAssetIcon get flipHorizontalBoldDuotone => FxAssetIcon(name: '$_path/flip-horizontal-bold-duotone');
  FxAssetIcon get flipHorizontalBold => FxAssetIcon(name: '$_path/flip-horizontal-bold');
  FxAssetIcon get flipHorizontalBroken => FxAssetIcon(name: '$_path/flip-horizontal-broken');
  FxAssetIcon get flipHorizontalLineDuotone => FxAssetIcon(name: '$_path/flip-horizontal-line-duotone');
  FxAssetIcon get flipHorizontalLinear => FxAssetIcon(name: '$_path/flip-horizontal-linear');
  FxAssetIcon get flipHorizontalOutline => FxAssetIcon(name: '$_path/flip-horizontal-outline');
  FxAssetIcon get flipVerticalBoldDuotone => FxAssetIcon(name: '$_path/flip-vertical-bold-duotone');
  FxAssetIcon get flipVerticalBold => FxAssetIcon(name: '$_path/flip-vertical-bold');
  FxAssetIcon get flipVerticalBroken => FxAssetIcon(name: '$_path/flip-vertical-broken');
  FxAssetIcon get flipVerticalLineDuotone => FxAssetIcon(name: '$_path/flip-vertical-line-duotone');
  FxAssetIcon get flipVerticalLinear => FxAssetIcon(name: '$_path/flip-vertical-linear');
  FxAssetIcon get flipVerticalOutline => FxAssetIcon(name: '$_path/flip-vertical-outline');
  FxAssetIcon get radialBlurBoldDuotone => FxAssetIcon(name: '$_path/radial-blur-bold-duotone');
  FxAssetIcon get radialBlurBold => FxAssetIcon(name: '$_path/radial-blur-bold');
  FxAssetIcon get radialBlurBroken => FxAssetIcon(name: '$_path/radial-blur-broken');
  FxAssetIcon get radialBlurLineDuotone => FxAssetIcon(name: '$_path/radial-blur-line-duotone');
  FxAssetIcon get radialBlurLinear => FxAssetIcon(name: '$_path/radial-blur-linear');
  FxAssetIcon get radialBlurOutline => FxAssetIcon(name: '$_path/radial-blur-outline');
  FxAssetIcon get rulerAngularBoldDuotone => FxAssetIcon(name: '$_path/ruler-angular-bold-duotone');
  FxAssetIcon get rulerAngularBold => FxAssetIcon(name: '$_path/ruler-angular-bold');
  FxAssetIcon get rulerAngularBroken => FxAssetIcon(name: '$_path/ruler-angular-broken');
  FxAssetIcon get rulerAngularLineDuotone => FxAssetIcon(name: '$_path/ruler-angular-line-duotone');
  FxAssetIcon get rulerAngularLinear => FxAssetIcon(name: '$_path/ruler-angular-linear');
  FxAssetIcon get rulerAngularOutline => FxAssetIcon(name: '$_path/ruler-angular-outline');
  FxAssetIcon get rulerBoldDuotone => FxAssetIcon(name: '$_path/ruler-bold-duotone');
  FxAssetIcon get rulerBold => FxAssetIcon(name: '$_path/ruler-bold');
  FxAssetIcon get rulerBroken => FxAssetIcon(name: '$_path/ruler-broken');
  FxAssetIcon get rulerCrossPenBoldDuotone => FxAssetIcon(name: '$_path/ruler-cross-pen-bold-duotone');
  FxAssetIcon get rulerCrossPenBold => FxAssetIcon(name: '$_path/ruler-cross-pen-bold');
  FxAssetIcon get rulerCrossPenBroken => FxAssetIcon(name: '$_path/ruler-cross-pen-broken');
  FxAssetIcon get rulerCrossPenLineDuotone => FxAssetIcon(name: '$_path/ruler-cross-pen-line-duotone');
  FxAssetIcon get rulerCrossPenLinear => FxAssetIcon(name: '$_path/ruler-cross-pen-linear');
  FxAssetIcon get rulerCrossPenOutline => FxAssetIcon(name: '$_path/ruler-cross-pen-outline');
  FxAssetIcon get rulerLineDuotone => FxAssetIcon(name: '$_path/ruler-line-duotone');
  FxAssetIcon get rulerLinear => FxAssetIcon(name: '$_path/ruler-linear');
  FxAssetIcon get rulerOutline => FxAssetIcon(name: '$_path/ruler-outline');
  FxAssetIcon get rulerPenBoldDuotone => FxAssetIcon(name: '$_path/ruler-pen-bold-duotone');
  FxAssetIcon get rulerPenBold => FxAssetIcon(name: '$_path/ruler-pen-bold');
  FxAssetIcon get rulerPenBroken => FxAssetIcon(name: '$_path/ruler-pen-broken');
  FxAssetIcon get rulerPenLineDuotone => FxAssetIcon(name: '$_path/ruler-pen-line-duotone');
  FxAssetIcon get rulerPenLinear => FxAssetIcon(name: '$_path/ruler-pen-linear');
  FxAssetIcon get rulerPenOutline => FxAssetIcon(name: '$_path/ruler-pen-outline');
  FxAssetIcon get threeSquaresBoldDuotone => FxAssetIcon(name: '$_path/three-squares-bold-duotone');
  FxAssetIcon get threeSquaresBold => FxAssetIcon(name: '$_path/three-squares-bold');
  FxAssetIcon get threeSquaresBroken => FxAssetIcon(name: '$_path/three-squares-broken');
  FxAssetIcon get threeSquaresLineDuotone => FxAssetIcon(name: '$_path/three-squares-line-duotone');
  FxAssetIcon get threeSquaresLinear => FxAssetIcon(name: '$_path/three-squares-linear');
  FxAssetIcon get threeSquaresOutline => FxAssetIcon(name: '$_path/three-squares-outline');
}
